version: '3'

networks:
  local_network:

services:
  php:
    container_name: php
    build:
      context: .
      dockerfile: ./containers/php/Dockerfile
    networks:
      - local_network
    volumes:
      - ./www:/www
      - ./etc/php/php.ini:/usr/local/etc/php/php.ini
      - ./etc/php/www.conf:/usr/local/etc/php-fpm.d/www.conf

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./www:/www
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./log/nginx:/var/log/nginx
    depends_on:
      - php
      - mysql
    networks:
      - local_network

  mysql:
    container_name: mysql
    image: mysql:5.7.22
    restart: unless-stopped
    tty: true
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./etc/mysql/my.cnf:/etc/mysql/my.cnf
      - ./log/mysql:/var/log/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: testy
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - local_network

  memcached:
    container_name: memcached
    image: memcached:latest
    networks:
      - local_network
    ports:
      - 11211:11211

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:6.4.1
    volumes:
    - ./data/elasticsearch:/usr/share/elasticsearch/data
    - ./log/elasticsearch:/usr/share/elasticsearch/logs
    - ./etc/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    - ./etc/elasticsearch/jvm.options:/usr/share/elasticsearch/config/jvm.options
    networks:
      - local_network
    ports:
      - 9200:9200
      - 9300:9300

